### PR TITLE
Add bearer token & link user to job posting

### PR DESCRIPTION
**Pull request by ryanji99**

### CODE REVIEW

**Review by brianMxBm — CHANGES_REQUESTED** [review]
jobController.ts:
I see that there's a structured request type _CustomExpressRequest_ with the type or, rather, an extension of the user schema. That type is then utilized for the create job controller to check if the content of the request contains the user type. A new job can then be created with the userID being associated with the job; great.

userController.ts:
If the user was successfully created with the data passed to the endpoint, you associate the JTW with the user's primary key (that being the _id); this would be used to authorize the user for certain actions in the backend, nice. You simplified the code I had written for the reset password function; simply utilizing the userID is nice! 

auth.ts:
Great work on the authentication; this is going to be extremely useful in cases when we want to ensure that endpoints are ONLY being hit by users signed up through the application. Could you possibly explain what's going on in this line, though?
 ` const user = await User.findById(decoded.id).select("-password");`

Requested Changes: 
Currently, the JobController.ts file throws a TypeScript error with the current type it's receiving. It reads: 
` const latitude: any Property 'latitude' does not exist on type 'ReadableStream<Uint8Array> | null'.`

**Comment by ryanji99** [comment]
> Could you possibly explain what's going on in this line, though? ` const user = await User.findById(decoded.id).select("-password");`

The JWT payload contains the user ID upon successful authentication. When the token is decoded, the payload can be accessed with `decoded.id` and that ID can in turn be used to query the User collection. The `select` method selects which fields are returned in the query. By providing `-password` as an argument, the password field is omitted from the query.

> Requested Changes: Currently, the JobController.ts file throws a TypeScript error with the current type it's receiving. It reads: ` const latitude: any Property 'latitude' does not exist on type 'ReadableStream<Uint8Array> | null'.`

Fixed ✅

**Review by katalla1 — APPROVED** [review]
Very nicely done Ryan.

**Comment by brianMxBm** [comment]
Well Done!

**Pull request merged**
